exports.assmas = {'person': 'человек',
			'bicycle': 'велосипед',
			'car': 'автомобиль',
			'motorbike': 'мотоцикл',
			'aeroplane': 'самолет',
			'bus': 'автобус',
			'train': 'поезд',
			'truck': 'грузовая машина',
			'boat': 'лодка',
			'traffic light': 'светофор',
			'fire hydrant': 'пожарный кран',
			'stop sign': 'знак СТОП',
			'parking meter': 'парковочный автомат',
			'bench': 'скамейка',
			'bird': 'птица',
			'cat': 'кошка',
			'dog': 'собака',
			'horse': 'лошадь',
			'sheep': 'овца',
			'cow': 'корова',
			'elephant': 'слон',
			'bear': 'медведь',
			'zebra': 'зебра',
			'giraffe': 'жираф',
			'backpack': 'рюкзак',
			'umbrella': 'зонтик',
			'handbag': 'сумка',
			'tie': 'галстук',
			'suitcase': 'чемодан',
			'frisbee': 'фрисби',
			'skis': 'лыжи',
			'snowboard': 'сноуборд',
			'sports ball': 'спортивный мяч',
			'kite': 'воздушный змей',
			'baseball bat': 'бейсбольная бита',
			'baseball glove': 'бейсбольная перчатка',
			'skateboard': 'скейтборд',
			'surfboard': 'доска для серфинга',
			'tennis racket': 'теннисная ракетка',
			'bottle': 'бутылка',
			'wine glass': 'бокал для вина',
			'cup': 'кружка',
			'fork': 'вилка',
			'knife': 'нож',
			'spoon': 'ложка',
			'bowl': 'миска',
			'banana': 'банан',
			'apple': 'яблоко',
			'sandwich': 'сэндвич',
			'orange': 'апельсин',
			'broccoli': 'брокколи',
			'carrot': 'морковь',
			'hot dog': 'хот-дог',
			'pizza': 'пицца',
			'donut': 'пончик',
			'cake': 'кекс',
			'chair': 'стул',
			'sofa': 'диван',
			'pottedplant': 'растение в горшке',
			'bed': 'постель',
			'diningtable': 'обеденный стол',
			'toilet': 'туалет',
			'tvmonitor': 'телевизионный монитор',
			'laptop': 'портативный компьютер',
			'mouse': 'мышь',
			'remote': 'дистанционный пульт',
			'keyboard': 'клавиатура',
			'cell phone': 'сотовый телефон',
			'microwave': 'микроволновая печь',
			'oven': 'печь',
			'toaster': 'тостер',
			'sink': 'раковина',
			'refrigerator': 'холодильник',
			'book': 'книга',
			'clock': 'часы',
			'vase': 'ваза',
			'scissors': 'ножницы',
			'teddy bear': 'плюшевый медведь',
			'hair drier': 'фен',
			'toothbrush': 'зубная щетка'
};
